on:
  push:
    branches:
      - main

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Check Upstream deployment
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/barnersh/upstream/releases \
               | grep "TSK-11"
