name: Issue Notification

on:
  issues:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Create Notion Issue
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.NOTION_INTEGRATION_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            https://api.notion.com/v1/pages \
            -d '{
              "parent": {
                "database_id": "1b24f7892901803b9615f947a0baad01"
              },
              "properties": {
                "Name": {
                  "title": [
                    {
                      "text": {
                        "content": "Tuscan Kale"
                      }
                    }
                  ]
                },
                "URL": {
                  "url": "${{ github.event.issue.html_url }}"
                }
              }
            }'

      - name: Trigger central repository
        run: |
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.DISPATCH_PAT_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/barnersh/upstream/dispatches \
              -d '{
                "event_type": "issue_opened_event",
                "client_payload": {
                  "title": "${{ github.event.issue.title }}",
                  "html_url": "${{ github.event.issue.html_url }}",
                  "repository": "${{ github.repository }}",
                  "description": "${{ github.event.issue.body }}"
                }
              }'