name: PR Notification

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare PR description
        id: prepare
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          ESCAPED_BODY=$(echo "$PR_BODY" | jq -Rs .)
          echo "ESCAPED_BODY=$ESCAPED_BODY" >> $GITHUB_ENV

      - name: Trigger central repository
        run: |
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.DISPATCH_PAT_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/barnersh/upstream/dispatches \
              -d '{
                "event_type": "pr_opened_event",
                "client_payload": {
                  "title": "${{ github.event.pull_request.title }}",
                  "number": "${{ github.event.pull_request.number }}",
                  "user": "${{ github.event.pull_request.user.login }}",
                  "html_url": "${{ github.event.pull_request.html_url }}",
                  "repository": "${{ github.repository }}",
                  "branch": "${{ github.event.pull_request.head.ref }}",
                  "base": "${{ github.event.pull_request.base.ref }}",
                  "description": '"$ESCAPED_BODY"'
                }
              }'